const COOKIE_KEY_TOKEN = '__i_token'
const SUPPORT_ACTIONS = ['@weibo', '@i']

const OAUTH_SCENE_EXTENSION = 'extension_home'
const OAUTH_SCENE_WEB_HOME = 'web_home'
const OAUTH_SCENE_WEB_TIMELINE = 'web_timeline'
const OAUTH_SCENE_WEB_SETTING = 'web_setting'
const OAUTH_SCENE_WEB_BINDING_WEIBO = 'web_binding_weibo'
const OAUTH_SCENE_WEB_BINDING_DROPBOX = 'web_binding_dropbox'
const OAUTH_SCENE_WEB_NOTFOUND = 'web_notfound'
const OAUTH_SCENE_WEB_ARTICLE = 'web_article'
const OAUTH_SCENE_IOS = 'ios_oauth'
const APP_BASE_URL = 'https://giki.app'

const SIZE_PER_PAGE = 20

module.exports = {
  COOKIE_KEY_TOKEN,
  SUPPORT_ACTIONS,

  OAUTH_SCENE_EXTENSION,
  OAUTH_SCENE_WEB_HOME,
  OAUTH_SCENE_WEB_TIMELINE,
  OAUTH_SCENE_WEB_SETTING,
  OAUTH_SCENE_WEB_BINDING_WEIBO,
  OAUTH_SCENE_WEB_BINDING_DROPBOX,
  OAUTH_SCENE_WEB_NOTFOUND,
  OAUTH_SCENE_WEB_ARTICLE,
  OAUTH_SCENE_IOS,

  SIZE_PER_PAGE,
  APP_BASE_URL,
}
